### ISSUE TITLE
QUESTION: How do I know which in app purchases are restored?

### ISSUE THREAD

**Issue by bynelus** [robotmedia/RMStore#106]
Hi,

Thank you for distributing this great framework. 

I would love to use it, but the only thing I'm missing right now is to find out which in app purchases are restored when I request to restore the previous purchased items. Could somebody point me to the right direction?

Thanks in advance!

**Comment by Sjoerdjanssenen** [comment]
Did you ever find an answer to this? @NielsKoole

**Comment by bynelus** [comment]
Yeah, this issue was about restoring pruchases with the block based method as I can remember. I switched over to the notification method where the notification object contains a list of restored purchases ids.
