### ISSUE TITLE
Back in February

### ISSUE THREAD

**Issue by hpique** [robotmedia/RMStore#133]
Heya. I haven't been able to work in this project lately, mostly due to the holidays and now vacation. I should be back to actively contributing in early February.

If you're comfortable with RMStore, I would greatly appreciate if you can respond to issues and help fellow RMStore users.

**Comment by fulldecent** [comment]
Welcome back, there are a few pull requests to help you. Also, please review contributors and please add one of them to have commit access here if you can trust them to keep the project moving.

**Comment by hpique** [comment]
Will do @fulldecent. Any suggestions?

**Comment by fulldecent** [comment]
@hpique Yes. I have been reviewing some of these PRs. I will leave a comment on the ones I have reviewed, tested, and can endorse.

**Comment by fulldecent** [comment]
Done. There are a lot of good, easy, one-click solutions waiting to happen here!
