### ISSUE TITLE
Multiple receipt verification calls from - (void)paymentQueue:(SKPaymentQueue *)queue updatedTransactions:(NSArray *)transactions

### ISSUE THREAD

**Issue by aksonov** [robotmedia/RMStore#146]
Very strange issue for auto-renewable transactions (sandbox) and remote server-verification. Bought in-app product (1 product to queue), verified successfully. Next app launch have 1 product verification during app startup (i.e. duplicated verification). Next launch - nothing (it is ok). But then again bought one in-app subscription, verified successfully. And next app launch have 2 verifications during app startup (i.e. 2 duplicated verification). For some reasons queue is growing after successful buy. Now i have 18 transactions, they disappeared after successful verification, but restored again after new buy.

**Comment by danimal** [comment]
I'm seeing this too. Did you find an answer @aksonov?

**Comment by LeeMatthewHiggins** [comment]
I'm also seeing this problem with auto-renewable.

**Comment by aksonov** [comment]
I found the reason actually - the problem that auto renewable sandbox is 5 min length. So you will have a lot of transactions. So this issue should not happen for production.
