### ISSUE TITLE
Dealing with slow (or no) access to iTunes Store

### ISSUE THREAD

**Issue by winzig** [robotmedia/RMStore#171]
Is there any mechanism for forcing a timeout or dealing with networking issues connecting to the App Store, e.g. after calling the addPayment method? 

We've run into issues where some users will initiate a payment, and due to network or other problems, they may be sitting there for many minutes with nothing happening. Is there any way for us to force a timeout after a reasonable wait, so they can re-initiate?

I saw this pull request which seemed to touch on it, but looks like it was rejected: https://github.com/robotmedia/RMStore/pull/60

**Comment by hpique** [comment]
Hi @winzig.

You can follow the approach in #60, for example. I don't foresee adding any timeout functionality to RMStore that is not already provided by StoreKit.
