### ISSUE TITLE
Restore Purchase is always successful, even when product has not been purchased

### ISSUE THREAD

**Issue by inPhilly** [robotmedia/RMStore#29]
I am testing on a device in iOS 7 in the sandbox. I logged out of my iTunes account and cleared the keychain data. I downloaded a fresh version of the app and used a brand new test account. I hit the Restore button for my non-consumable product. I was asked to enter my iTunes ID and password twice, even though I am positive I entered it correctly the first time. The product was then restored successfully, even though it had not yet been purchased by this test account user. I tried this with multiple test accounts and it is reproducible every time.

**Comment by vgolovnev** [comment]
Hello. Could you please add this information to Readme? How could I know this? Developers can be misled. Otherwise, this framework is very useful. Many thanks.
