### ISSUE TITLE
Build fails unless you link libssl and libcrypto libraries with the Pods-RMStore target

### ISSUE THREAD

**Issue by mmorey** [robotmedia/RMStore#37]
When running `pod install` for the first time on a project with RMStore the project will not build. You have to link the Pods-RMStore target in the Pods project with the libssl and libcrypto libraries.

Relevant portion of build log:

```
(null): "_d2i_PKCS7_fp", referenced from:
(null): +[RMAppReceipt dataFromPCKS7Path:] in libPods.a(RMAppReceipt.o)
(null): "_SHA1", referenced from:
(null): -[RMAppReceipt verifyReceiptHash] in libPods.a(RMAppReceipt.o)
(null): "_PKCS7_free", referenced from:
(null): +[RMAppReceipt dataFromPCKS7Path:] in libPods.a(RMAppReceipt.o)
(null): "_ASN1_get_object", referenced from:
(null): _RMASN1ReadInteger in libPods.a(RMAppReceipt.o)
(null): _RMASN1ReadOctectString in libPods.a(RMAppReceipt.o)
(null): _RMASN1ReadString in libPods.a(RMAppReceipt.o)
(null): +[RMAppReceipt enumerateASN1Attributes:length:usingBlock:] in libPods.a(RMAppReceipt.o)
(null): Symbol(s) not found for architecture armv7s
(null): Linker command failed with exit code 1 (use -v to see invocation)
```

Podfile:

```
platform :ios, '7.0'
pod 'RMStore', '~> 0.4.2'
```

**Comment by foffux** [comment]
Just to add some more comments about this issue, I also experimented the same one. The solution suggested by Paul Taykalo did not work for me. Take a look at the picture attached.
Also what hpique said is not valid for me. Take a look at the picture attached again.
To fix my issue I had to do how mmorey suggested, i.e. manually add those library to my project. But I am wondering if this is the right way to do things or if I could have some more issues in the future.
![schermata 2015-02-01 alle 11 28 15](https://cloud.githubusercontent.com/assets/8709479/5991777/6f9a4c3c-aa05-11e4-963e-bf7cac091a4d.png)
![schermata 2015-02-01 alle 11 29 40](https://cloud.githubusercontent.com/assets/8709479/5991779/a63b0bbe-aa05-11e4-985d-eff382e0514e.png)

**Comment by Dids** [comment]
I can 'pod install' just fine and OpenSSL builds without a hitch.

My issues is that my own library (that uses RMStore) doesn't build. I get the same undefined symbols as with the original issue here. Both 'pod lib lint' and 'pod spec lint' produce this error, when running with '--verbose'.

The only change I can see here is that I'm targeting iOS 7 (in both podspec and Podfile), but OpenSSL is building for iPhone OS 8.2 (successfully), but then is unable to link with the project after that.

Anyone have any ideas, clues or tips?
