### ISSUE TITLE
User tapping "cancel" on purchase throws error

### ISSUE THREAD

**Issue by ghost** [robotmedia/RMStore#39]
When the user taps to purchase a product in my app, I run:

```
        NSString *productId = @"myProductId";
        [[RMStore defaultStore] addPayment:productId success:^(SKPaymentTransaction *transaction) {
            NSLog(@"Product purchased: %@", productId);
            // ... do stuff here
        } failure:^(SKPaymentTransaction *transaction, NSError *error) {
            NSLog(@"Purchase failed: %@", error);
            // ... throw an error here
        }];
```

This works great under most circumstances. However when the user is prompted for the password, and then taps the 'cancel' button, the failure block is called. Is it possible to determine that it was not a system failure, but rather that the user simply decided to cancel?

**Comment by pahnev** [comment]
Yup, it gives: Error Domain=SKErrorDomain Code=2 "Cannot connect to iTunes Store" UserInfo=0x155d1430 {NSLocalizedDescription=Cannot connect to iTunes Store

I hope it won't be that when it can't actually connect to the store. I think there should be a separate notification for cancel.

**Comment by Dids** [comment]
I'm also experiencing this, but only tried canceling while on the purchase screen/prompt. Throws the same error though.
