### ISSUE TITLE
[[RMAppReceipt bundleReceipt] originalAppVersion] returns no value (on sandbox)

### ISSUE THREAD

**Issue by Nonnus** [robotmedia/RMStore#51]
although this is stated in RMAppReceipt.h

/*\* The version of the app that was originally purchased. This corresponds to the value of CFBundleVersion (in iOS) or CFBundleShortVersionString (in OS X) in the Info.plist file when the purchase was originally made. In the sandbox environment, the value of this field is always “1.0”.
 */
@property (nonatomic, strong, readonly) NSString *originalAppVersion;

when i use it on test environment (sandbox) i get no value returned, no "1.0" string as state, is this normal? can i trust it to work properly on production code ?

**Comment by cerupcat** [comment]
@hpique What was the verdict on this? Is it possible to get the receipt when testing in sandbox? For me, "appStoreReceiptURL" is always to a local file ending with "sandboxReceipt" but it's always nil when trying to open the file.
