### ISSUE TITLE
RMStore/AppReceiptVerificator issue with OpenSSL

### ISSUE THREAD

**Issue by Calvinchinzs** [robotmedia/RMStore#77]
Hi guys,

First of, thank you so much for providing us this framework.

I'm having issues using the latest version of 0.5.0 with RMStore/AppReceiptVerificator. Below is the log i'm getting as well as the specs I have.

Cocoapods - Version 0.33.1
Podfile - RMStore/AppReceiptVerificator
Xocde - Version 5.1.1 (I have iOS 7.1 simulator)
OpenSSL version - 1.0.1g 
# Pods config file.

CLANG_CXX_LANGUAGE_STANDARD = c++11
CLANG_CXX_LIBRARY = libc++
FRAMEWORK_SEARCH_PATHS = "$(PODS_ROOT)/Parse"
GCC_PREPROCESSOR_DEFINITIONS = $(inherited) COCOAPODS=1
HEADER_SEARCH_PATHS = "${PODS_ROOT}/Headers" "${PODS_ROOT}/Headers/AFNetworking" "${PODS_ROOT}/Headers/ARAnalytics" "${PODS_ROOT}/Headers/BPXLUUIDHandler" "${PODS_ROOT}/Headers/Bolts" "${PODS_ROOT}/Headers/DACircularProgress" "${PODS_ROOT}/Headers/DDiCloudSync" "${PODS_ROOT}/Headers/Facebook-iOS-SDK" "${PODS_ROOT}/Headers/Facebook-iOS-SDK/FacebookSDK" "${PODS_ROOT}/Headers/FlurrySDK" "${PODS_ROOT}/Headers/GoogleAnalytics-iOS-SDK" "${PODS_ROOT}/Headers/MZTimerLabel" "${PODS_ROOT}/Headers/Mixpanel" "${PODS_ROOT}/Headers/Parse" "${PODS_ROOT}/Headers/RMStore" "${PODS_ROOT}/Headers/Reachability" "${PODS_ROOT}/Headers/TestFlightSDK" "${PODS_ROOT}/Headers/pop" $(SDKROOT)/usr/include/libz
LIBRARY_SEARCH_PATHS = "$(PODS_ROOT)/FlurrySDK/Flurry" "$(PODS_ROOT)/GoogleAnalytics-iOS-SDK" "$(PODS_ROOT)/TestFlightSDK"
OTHER_CFLAGS = $(inherited) -isystem "${PODS_ROOT}/Headers" -isystem "${PODS_ROOT}/Headers/AFNetworking" -isystem "${PODS_ROOT}/Headers/ARAnalytics" -isystem "${PODS_ROOT}/Headers/BPXLUUIDHandler" -isystem "${PODS_ROOT}/Headers/Bolts" -isystem "${PODS_ROOT}/Headers/DACircularProgress" -isystem "${PODS_ROOT}/Headers/DDiCloudSync" -isystem "${PODS_ROOT}/Headers/Facebook-iOS-SDK" -isystem "${PODS_ROOT}/Headers/Facebook-iOS-SDK/FacebookSDK" -isystem "${PODS_ROOT}/Headers/FlurrySDK" -isystem "${PODS_ROOT}/Headers/GoogleAnalytics-iOS-SDK" -isystem "${PODS_ROOT}/Headers/MZTimerLabel" -isystem "${PODS_ROOT}/Headers/Mixpanel" -isystem "${PODS_ROOT}/Headers/Parse" -isystem "${PODS_ROOT}/Headers/RMStore" -isystem "${PODS_ROOT}/Headers/Reachability" -isystem "${PODS_ROOT}/Headers/TestFlightSDK" -isystem "${PODS_ROOT}/Headers/pop"
OTHER_LDFLAGS = -ObjC -lFlurry_5.0.0 -lGoogleAnalyticsServices -lTestFlight -lc++ -lsqlite3 -lz -framework Accelerate -framework AudioToolbox -framework CFNetwork -framework CoreData -framework CoreGraphics -framework CoreLocation -framework CoreTelephony -framework Foundation -framework MediaPlayer -framework MobileCoreServices -framework Parse -framework QuartzCore -framework Security -framework StoreKit -framework SystemConfiguration -framework UIKit -weak_framework Accounts -weak_framework AdSupport -weak_framework Security -weak_framework Social -weak_framework StoreKit
# PODS_ROOT = ${SRCROOT}/Pods

> Running prepare command
>    $ /bin/bash
>    set -e

   VERSION="1.0.1g"
   SDKVERSION=`/usr/bin/xcodebuild -version -sdk 2> /dev/null | grep SDKVersion | tail -n 1 |  awk '{ print $2 }'`

   CURRENTPATH=`pwd`
   ARCHS="i386 x86_64 armv7 armv7s arm64"
   DEVELOPER=`xcode-select -print-path`

   mkdir -p "${CURRENTPATH}/bin"
   mkdir -p "${CURRENTPATH}/lib"
   mkdir -p "${CURRENTPATH}/openssl"

   hash=$(cat file.tgz | openssl dgst -sha1 | sed 's/^.\* //')

   if [ "$hash" != "b28b3bcb1dc3ee7b55024c9f795be60eb3183e3c" ]; then
     echo "OpenSSL downloaded doesn't seem valid"
     exit 1;
   fi

   tar -xzf file.tgz

   cd openssl-${VERSION}

   for ARCH in ${ARCHS}
   do

```
 CONFIGURE_FOR="iphoneos-cross"

 if [ "${ARCH}" == "i386" ] || [ "${ARCH}" == "x86_64" ] ;
 then
   PLATFORM="iPhoneSimulator"
   if [ "${ARCH}" == "x86_64" ] ;
   then
     CONFIGURE_FOR="darwin64-x86_64-cc"
   fi
 else
   sed -ie "s!static volatile sig_atomic_t intr_signal;!static volatile intr_signal;!" "crypto/ui/ui_openssl.c"
   PLATFORM="iPhoneOS"
 fi

 export CROSS_TOP="${DEVELOPER}/Platforms/${PLATFORM}.platform/Developer"
 export CROSS_SDK="${PLATFORM}${SDKVERSION}.sdk"

 echo "Building openssl-${VERSION} for ${PLATFORM} ${SDKVERSION} ${ARCH}"
 echo "Please stand by..."

 export CC="${DEVELOPER}/usr/bin/gcc -arch ${ARCH} -miphoneos-version-min=${SDKVERSION}"
 mkdir -p "${CURRENTPATH}/bin/${PLATFORM}${SDKVERSION}-${ARCH}.sdk"
 LOG="${CURRENTPATH}/bin/${PLATFORM}${SDKVERSION}-${ARCH}.sdk/build-openssl-${VERSION}.log"

 ./Configure ${CONFIGURE_FOR} --openssldir="${CURRENTPATH}/bin/${PLATFORM}${SDKVERSION}-${ARCH}.sdk" > "${LOG}" 2>&1
 sed -ie "s!^CFLAG=!CFLAG=-isysroot ${CROSS_TOP}/SDKs/${CROSS_SDK} !" "Makefile"

 make >> "${LOG}" 2>&1
 make install >> "${LOG}" 2>&1
 make clean >> "${LOG}" 2>&1
```

   done

   echo "Build library..."
   lipo -create ${CURRENTPATH}/bin/iPhoneSimulator${SDKVERSION}-i386.sdk/lib/libssl.a
   ${CURRENTPATH}/bin/iPhoneSimulator${SDKVERSION}-x86_64.sdk/lib/libssl.a  ${CURRENTPATH}/bin/iPhoneOS${SDKVERSION}-armv7.sdk/lib/libssl.a
   ${CURRENTPATH}/bin/iPhoneOS${SDKVERSION}-armv7s.sdk/lib/libssl.a ${CURRENTPATH}/bin/iPhoneOS${SDKVERSION}-arm64.sdk/lib/libssl.a -output
   ${CURRENTPATH}/lib/libssl.a
   lipo -create ${CURRENTPATH}/bin/iPhoneSimulator${SDKVERSION}-i386.sdk/lib/libcrypto.a
   ${CURRENTPATH}/bin/iPhoneSimulator${SDKVERSION}-x86_64.sdk/lib/libcrypto.a
   ${CURRENTPATH}/bin/iPhoneOS${SDKVERSION}-armv7.sdk/lib/libcrypto.a ${CURRENTPATH}/bin/iPhoneOS${SDKVERSION}-armv7s.sdk/lib/libcrypto.a
   ${CURRENTPATH}/bin/iPhoneOS${SDKVERSION}-arm64.sdk/lib/libcrypto.a -output ${CURRENTPATH}/lib/libcrypto.a

   echo "Building done."
   echo "Cleaning up..."
   rm -rf ${CURRENTPATH}/openssl-${VERSION}
   rm -R ${CURRENTPATH}/bin
   rm -rf file.tgz
   echo "Done."
   Building openssl-1.0.1g for iPhoneSimulator 7.1 i386
   Please stand by...
[!] /bin/bash
set -e

VERSION="1.0.1g"
SDKVERSION=`/usr/bin/xcodebuild -version -sdk 2> /dev/null | grep SDKVersion | tail -n 1 |  awk '{ print $2 }'`

CURRENTPATH=`pwd`
ARCHS="i386 x86_64 armv7 armv7s arm64"
DEVELOPER=`xcode-select -print-path`

mkdir -p "${CURRENTPATH}/bin"
mkdir -p "${CURRENTPATH}/lib"
mkdir -p "${CURRENTPATH}/openssl"

hash=$(cat file.tgz | openssl dgst -sha1 | sed 's/^.\* //')

if [ "$hash" != "b28b3bcb1dc3ee7b55024c9f795be60eb3183e3c" ]; then
  echo "OpenSSL downloaded doesn't seem valid"
  exit 1;
fi

tar -xzf file.tgz

cd openssl-${VERSION}

for ARCH in ${ARCHS}
do

  CONFIGURE_FOR="iphoneos-cross"

  if [ "${ARCH}" == "i386" ] || [ "${ARCH}" == "x86_64" ] ;
  then
    PLATFORM="iPhoneSimulator"
    if [ "${ARCH}" == "x86_64" ] ;
    then
      CONFIGURE_FOR="darwin64-x86_64-cc"
    fi
  else
    sed -ie "s!static volatile sig_atomic_t intr_signal;!static volatile intr_signal;!" "crypto/ui/ui_openssl.c"
    PLATFORM="iPhoneOS"
  fi

  export CROSS_TOP="${DEVELOPER}/Platforms/${PLATFORM}.platform/Developer"
  export CROSS_SDK="${PLATFORM}${SDKVERSION}.sdk"

  echo "Building openssl-${VERSION} for ${PLATFORM} ${SDKVERSION} ${ARCH}"
  echo "Please stand by..."

  export CC="${DEVELOPER}/usr/bin/gcc -arch ${ARCH} -miphoneos-version-min=${SDKVERSION}"
  mkdir -p "${CURRENTPATH}/bin/${PLATFORM}${SDKVERSION}-${ARCH}.sdk"
  LOG="${CURRENTPATH}/bin/${PLATFORM}${SDKVERSION}-${ARCH}.sdk/build-openssl-${VERSION}.log"

  ./Configure ${CONFIGURE_FOR} --openssldir="${CURRENTPATH}/bin/${PLATFORM}${SDKVERSION}-${ARCH}.sdk" > "${LOG}" 2>&1
  sed -ie "s!^CFLAG=!CFLAG=-isysroot ${CROSS_TOP}/SDKs/${CROSS_SDK} !" "Makefile"

  make >> "${LOG}" 2>&1
  make install >> "${LOG}" 2>&1
  make clean >> "${LOG}" 2>&1
done

echo "Build library..."
lipo -create ${CURRENTPATH}/bin/iPhoneSimulator${SDKVERSION}-i386.sdk/lib/libssl.a ${CURRENTPATH}/bin/iPhoneSimulator${SDKVERSION}-x86_64.sdk/lib/libssl.a  ${CURRENTPATH}/bin/iPhoneOS${SDKVERSION}-armv7.sdk/lib/libssl.a ${CURRENTPATH}/bin/iPhoneOS${SDKVERSION}-armv7s.sdk/lib/libssl.a ${CURRENTPATH}/bin/iPhoneOS${SDKVERSION}-arm64.sdk/lib/libssl.a -output ${CURRENTPATH}/lib/libssl.a
lipo -create ${CURRENTPATH}/bin/iPhoneSimulator${SDKVERSION}-i386.sdk/lib/libcrypto.a ${CURRENTPATH}/bin/iPhoneSimulator${SDKVERSION}-x86_64.sdk/lib/libcrypto.a ${CURRENTPATH}/bin/iPhoneOS${SDKVERSION}-armv7.sdk/lib/libcrypto.a ${CURRENTPATH}/bin/iPhoneOS${SDKVERSION}-armv7s.sdk/lib/libcrypto.a ${CURRENTPATH}/bin/iPhoneOS${SDKVERSION}-arm64.sdk/lib/libcrypto.a -output ${CURRENTPATH}/lib/libcrypto.a

echo "Building done."
echo "Cleaning up..."
rm -rf ${CURRENTPATH}/openssl-${VERSION}
rm -R ${CURRENTPATH}/bin
rm -rf file.tgz
echo "Done."

Building openssl-1.0.1g for iPhoneSimulator 7.1 i386

Please stand by...

/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/lib/cocoapods/executable.rb:74:in `execute_command'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/lib/cocoapods/executable.rb:30:in`block in executable'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/lib/cocoapods/installer/pod_source_installer.rb:146:in `block (2 levels) in run_prepare_command'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/lib/cocoapods/installer/pod_source_installer.rb:142:in`chdir'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/lib/cocoapods/installer/pod_source_installer.rb:142:in `block in run_prepare_command'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/lib/cocoapods/user_interface.rb:52:in`section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/lib/cocoapods/installer/pod_source_installer.rb:141:in `run_prepare_command'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/lib/cocoapods/installer/pod_source_installer.rb:65:in`install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/lib/cocoapods/installer.rb:274:in `install_source_of_pod'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/lib/cocoapods/installer.rb:248:in`block (2 levels) in install_pod_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/lib/cocoapods/user_interface.rb:73:in `titled_section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/lib/cocoapods/installer.rb:247:in`block in install_pod_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/lib/cocoapods/installer.rb:239:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/lib/cocoapods/installer.rb:239:in`install_pod_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/lib/cocoapods/installer.rb:107:in `block in download_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/lib/cocoapods/user_interface.rb:52:in`section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/lib/cocoapods/installer.rb:105:in `download_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/lib/cocoapods/installer.rb:90:in`install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/lib/cocoapods/command/project.rb:40:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/lib/cocoapods/command/project.rb:70:in`run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.6.1/lib/claide/command.rb:281:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/lib/cocoapods/command.rb:48:in`run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/bin/pod:33:in `<top (required)>'
/usr/bin/pod:23:in`load'
/usr/bin/pod:23:in `<main>'
# 

Additional information:
After the process ended, I tried building via Xcode, Apparently, all my libraries stopped working. Technically speaking, if i were to run 'pod install' again when previously it was successful, by right there should not be any new installation, but the openssl installation repeated.

Please advice. Thanks!

**Comment by swinghu** [comment]
@NielsKoole ,cannot resolve my problem

**Comment by felipesabino** [comment]
@swinghu Did you manage to solve your problem? I am having the same issue with `openssl`...
