### ISSUE TITLE
RMStore crash when purchasing

### ISSUE THREAD

**Issue by sophyandres** [robotmedia/RMStore#82]
Hi, I have a basic installation of RMStore and my app crashes after I run the add payment call. Can you help?
The error looks like this:
2014-05-29 13:47:38.731 App[5874:60b] completeTransaction...
2014-05-29 13:47:38.761App[5874:60b] RMStore: transaction purchased with product com.App.offlinedata
2014-05-29 13:47:38.762 CheapEatParis[5874:60b] RMStore: WARNING: no receipt verification
2014-05-29 13:47:39.623 App[5874:60b] Validation successful
2014-05-29 13:47:39.623 App[5874:60b] Successfully verified receipt!
2014-05-29 13:47:39.631 App[5874:60b] -[__NSCFConstantString productIdentifier]: unrecognized selector sent to instance 0x2dd0d4
2014-05-29 13:47:39.632 App[5874:60b] **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFConstantString productIdentifier]: unrecognized selector sent to instance 0x2dd0d4'

My code is the following:

 _products = @[@"offlinecep",@"com.App.offlinedata"];

```
[UIApplication sharedApplication].networkActivityIndicatorVisible = YES;

[[RMStore defaultStore] requestProducts:[NSSet setWithArray:_products] success:^(NSArray *products, NSArray *invalidProductIdentifiers) {
    NSLog(@"invalid %@",invalidProductIdentifiers);
    NSLog(@"valid %@",products);
    [UIApplication sharedApplication].networkActivityIndicatorVisible = NO;
    _productsRequestFinished = YES;



} failure:^(NSError *error) {
    [UIApplication sharedApplication].networkActivityIndicatorVisible = NO;
    UIAlertView *alertView = [[UIAlertView alloc] initWithTitle:NSLocalizedString(@"Products Request Failed", @"")
                                                        message:error.localizedDescription
                                                       delegate:nil
                                              cancelButtonTitle:NSLocalizedString(@"OK", @"")
                                              otherButtonTitles:nil];
    [alertView show];
}];
```

and in purchase method:

-(IBAction)Upgrade:(id)sender{
 if (![RMStore canMakePayments]) return;
    [[RMStore defaultStore] addPayment:@"com.App.offlinedata" success:^(SKPaymentTransaction *transaction) {
        [UIApplication sharedApplication].networkActivityIndicatorVisible = NO;

```
} failure:^(SKPaymentTransaction *transaction, NSError *error) {
    [UIApplication sharedApplication].networkActivityIndicatorVisible = NO;
    UIAlertView *alerView = [[UIAlertView alloc] initWithTitle:NSLocalizedString(@"Payment Transaction Failed", @"")
                                                       message:error.localizedDescription
                                                      delegate:nil
                                             cancelButtonTitle:NSLocalizedString(@"OK", @"")
                                             otherButtonTitles:nil];
    [alerView show];
}];
```

}

**Comment by abduljamil** [comment]
For me it is crashing on line:     [_productsRequestDelegates addObject:delegate];
